"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
import os
sys.setrecursionlimit(1500)
APP = ['main.py']
DATA_FILES = []
for folder in ['src', 'ckpt']:
    for root, dirs, files in os.walk(folder):
        for file in files:
            DATA_FILES.append((root, [os.path.join(root, file)]))
print(DATA_FILES)

OPTIONS = {
    'argv_emulation': False,
    'packages': [
        'matplotlib',
        'mne',
        'numpy',
        'p_tqdm',
        'pandas',
        'openpyxl',
        'pyqt5',  # Uncomment this if PyQt5 is a dependency
        #'PyQt5_sip',
        'pyqtgraph',
        'scipy',
        #'scikit-image',
        # 'torch',
        # 'torchvision',
        'xy'
        "chardet",
        'tqdm',
        'ctypes'
    ],
    'includes': ['liblzma'],
    #'frameworks': ['/Users/yipengzhang/miniconda3/lib/liblzma.5.dylib'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['torch','torchvision'],
)
